### ISSUE TITLE
Folder Edit Details side-panel

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-asset-admin#156]
I’ve pulled down the latest versions of cms, framework and asset-admin and I can’t seem to find this functionality anywhere 

https://projects.invisionapp.com/boards/9GX68PTXUQFH#/1547737/71606997

TODO: Split out card to check if files are associated with published objects (e.g. pages), with a smarter warning message. Same behaviour needs to be applied to existing multi-select of files.

# Tasks

 * [x] Paul to spell out use cases (navigating up/down, opening/closing sidebar through different triggers)
 * [x] "Edit" trigger in breadcrumbs
 * [x] Save renames the folder and updates the gallery/breadcrumb view (with new name returned from server)
 * [x] Retrieve folder form fields through FormBuilder
 * [x] Readonly view of folder location

Ensure title is a required field (via HTML5) is covered by Framework #5523

# Acceptance Criteria
* To trigger the panel to open the edit icon is clicked (which is to the right side of the folder name in the north toolbar) See https://projects.invisionapp.com/boards/WEX68PM3XJ2N/
* To close the panel you can select the X within the folder edit panel
* The panel should contain:
  * Folder name at the top
  * Close icon top right corner
  * Thumbnail of folder (nice to have for alpha 2)
  * Folder name field
  * Readonly field for folder location
  * Save button
* On save the panel remains open, but if the folder name has changed:
  * the folder name in the north toolbar should update
  * the name at the top of the edit panel should update
* If files are selected when "edit folder" is chosen, all files are deselected
 * A folder can be deleted through a button on the form (with a generic confirmation), regardless of files being published with pages (same behaviour as SS3)

**Comment by chillu** [comment]
This is in `admin/assets`, rather than `admin/old-assets`, right?

**Comment by axyr** [comment]
I can confirm this is in the new admin/assets

**Comment by kinglozzer** [comment]
@chillu Yeah, new one

**Comment by flamerohr** [comment]
Pull requests for this story
https://github.com/silverstripe/silverstripe-framework/pull/5917
https://github.com/silverstripe/silverstripe-asset-admin/pull/233

**Comment by flamerohr** [comment]
pull requests are ready for peer review coding/javascript-wise
I'm refactoring the css to be BEM and standard across the non-legacy changes

**Comment by chillu** [comment]
@flamerohr Fixed icon positioning, wanna give it a quick review? https://github.com/silverstripe/silverstripe-framework/pull/5929
