### ISSUE TITLE
File details moved to side-bar

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-asset-admin#167]
As a user I would like to see and edit the details of a file in a sidebar.

## Acceptance Criteria

 * File details shown in a side-bar, rather than a separate view.

## Tasks

 * [x] Adapt sidebar styling from existing pull request (https://github.com/silverstripe/silverstripe-asset-admin/pull/107)
 * [x] Sidebar layout and responsive view
 * [x] Use Bootstrap styled text fields (incl. compressed label style)
 * [x] Convert classes from pull request to BEM, add into existing component structure
 * [x] Style close icon
 * [x] Restyle "properties" section (moved to hidden tab)
 * [x] Batch actions functional on smaller screens
 * [x] Dropzone component class naming (convert to BEM)
 * [x] Browser testing

## Excludes

 * Magnification
 * Sticky footer
 * Additional actions (dot-dot-dot)
 * "Usage" tab

## Resources

 * [Designs](https://projects.invisionapp.com/boards/9GX68PTXUQFH#/1547737)

## Related

 * [Edit/rename folders](https://github.com/silverstripe/silverstripe-asset-admin/issues/156)

**Comment by sminnee** [comment]
Internal cross-ref: https://silverstripe.atlassian.net/browse/OSS-1589

**Comment by clarkepaul** [comment]
I've got everything into the branch https://github.com/open-sausages/silverstripe-asset-admin/commits/features/4.0/details-sidebar but it requires framework branch  also https://github.com/open-sausages/silverstripe-framework/tree/features/4.0/details-sidebar

I got a bit trigger happy with all the changes in this branch so it also includes a fair bit of BEM tidy up.

Somehow the ability to add folders has broken (requires a browser refresh to see them). I had done browser testing over the last few days but things have changed a fair bit since then so another round should be required once all dev is complete.

**Comment by clarkepaul** [comment]
So far I've found some small issues in IE10 which I need to fix or create new issues for.
 * [ ] Magnifying glass has underline on hover
 * [ ] Text in input is cut off
 * [ ] Editor preview image needs -ms prefix on display: flex

**Comment by clarkepaul** [comment]
Ready for review

**Comment by clarkepaul** [comment]
I've added a fix for double scrollbar #175
