### ISSUE TITLE
Implement file publish control actions

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-asset-admin#169]
## Acceptance criteria

 * Action toolbar and options available on the file details match closely to the page button (see Paul's designs for more details)

## Tasks

 * [X] Implement unpublish action on "File" section (no indication in UI at the moment)
 * [X] Remove unpublish action when file is already unpublished
 * [ ] Merge https://github.com/silverstripe/silverstripe-asset-admin/pull/280

## Related

 * https://github.com/silverstripe/silverstripe-framework/issues/5529#issuecomment-218970412
 * https://github.com/silverstripe/silverstripe-framework/issues/5611
 * [Design UX Patterns](https://github.com/silverstripe/silverstripe-asset-admin/issues/219)

**Comment by tractorcow** [comment]
WIP on these branches

https://github.com/open-sausages/silverstripe-framework/tree/pulls/4.0/assets-custom-actions
https://github.com/open-sausages/silverstripe-asset-admin/tree/pulls/4.0/assets-custom-actions

**Comment by tractorcow** [comment]
PR at https://github.com/silverstripe/silverstripe-asset-admin/pull/280

**Comment by flamerohr** [comment]
Pull request is ready for merging
