### ISSUE TITLE
Routing and view support for file edit sidebar

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#170]
## Excludes

 * CSS or styling work (see https://github.com/silverstripe/silverstripe-asset-admin/issues/167)
 * No title update in gallery tile on edit (needs save)

## Tasks

- [x] Show both sidebar and current folder view when deep linked (`admin/assets/show/0/edit/3`).
- [x] Persist current "view" (edit or view) in component props, use redux action to trigger view variation (similar to CampaignAdmin)
- [x] Allow "close" on sidebar, updating the component prop "view"
- [x] Keep "selected files" (one or more) separate from "currently viewed file" (only one) in Redux state
- [x] Back navigation should close and open sidebar as required
- [x] Fix unit tests
- [x] Fix regression where files stay selected on folder navigation
- [ ] ~~Fix IE regression where URL doesn't change~~ (moved to https://github.com/silverstripe/silverstripe-asset-admin/issues/188)

**Comment by clarkepaul** [comment]
When you change images before saving the content from the previous image sticks and isn't swapped out for newly selected item.
![pasted_image_2_06_16__3_53_pm](https://cloud.githubusercontent.com/assets/555033/15733498/7f50b0e4-28da-11e6-9374-cef26e208e1e.png)

**Comment by chillu** [comment]
Fixed with https://github.com/silverstripe/silverstripe-asset-admin/pull/178 and https://github.com/silverstripe/silverstripe-framework/pull/5652. @clarkepaul Can you please file a new issue for the swap out bug you described above?

**Comment by clarkepaul** [comment]
@chillu The issue I stated above no longer seems to be an issue, so I wont open a new issue.
