### ISSUE TITLE
New-style Insert Media dialog

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-asset-admin#173]
## Acceptance criteria

 - The insert media dialog matches the look and feel of the new asset-admin section
 - I can upload one or more files prior to inserting it
 - The last of mulitple uploaded files is auto-selected and shows in the sidebar ready to insert
 - The multi-select abilities are removed
 - We have at least 1 behat test

Exclusion

 - No multi-file insert feature. It never made any sense
 - Insert from URL (separate story)
 - Filter files by images (https://github.com/silverstripe/silverstripe-asset-admin/issues/121)

---

Insert media link triggers the files area to appear in a pop up modal. Refer to https://projects.invisionapp.com/boards/6GX68P9YKERH/ 

Ideally, this would be part of the asset-admin module, which would add the relevant toolbar item to the CMS. Otherwise, we introduce a dependency form HTMLEditorField to asset-admin.

# Tasks
- [x] Refactor `<AssetAdmin>`, `<Gallery>` and  `<Editor>` to work standalone (or load entire admin/assets into an iframe)
- [x] Get AssetAdmin to appear on the pages section using entwine
- [x] Create "Insert" form (using a different React component based on `<Editor>`, but with `HtmlEditorField` form field schema)
- [x] Edit details on Insert form (to be confirmed)
- [x] ~Determine Generate shortcode logic~ (not required for this story, as tinymce plugin handles shortcode)
- [x] Insert images
- [x] Checkboxes are not available for modal
- [x] Uploading files, the latest file is selected/opened in Editor. (NOTE: this only opens the last file that finished uploading, so it can be a little unpredictable...)
- [x] Docblocks
- [x] Unit tests
- [x] Behat tests

# Excludes
- Recently edited files

# Blockers
- Behat async behaviours
- Components using FormBuilderLoader cannot have unit tests due to jest mocking errors

**Comment by marcello-silverstripe** [comment]
Chris and Paul to write stories for "Insert from URL" (OEmbed) and "Insert link", potentially design refresh with retaining current Entwine UI.

**Comment by marcello-silverstripe** [comment]
Paul to determine if "Details" tab should show readonly, and how we deal with different semantics for "Title" fields (title on link of this particular instance vs. title on the file record itself)

**Comment by clarkepaul** [comment]
Edit details design for placing files: There are a few ways we could have gone with this but I think if we limit what they can edit when placing the image the UI will be less confusing. 

https://projects.invisionapp.com/boards/9GX68PNAM62Y/

I think we can also limit the moving of files while within the Insert dialogue window (when drag drop is fully completed), we have also removed multi select so this area has limited functionality except for the inserting of images.

**Comment by flamerohr** [comment]
Pull requests made for this story:
- https://github.com/silverstripe/silverstripe-asset-admin/issues/307
- https://github.com/silverstripe/silverstripe-framework/issues/6317

**Comment by clarkepaul** [comment]
On the details tab and usage tab its weird having the "insert" on all tabs unless we fix it to the bottom so it doesn't clash with the "edit original" button on the details tab.

I'll see if can add the fixed toolbar.

**Comment by clarkepaul** [comment]
I've created a new issue which aims to remove the main action from the edit panel tabs, or alternatively adds the main action to a sticky toolbar at the bottom so that it isn't associated just to the tab content but the whole panel. Issue https://github.com/silverstripe/silverstripe-asset-admin/issues/310

**Comment by clarkepaul** [comment]
Browser tested and reviewed UX of which I'm happy with.

**Comment by tractorcow** [comment]
Reviewing now.

**Comment by tractorcow** [comment]
Merged!
