### ISSUE TITLE
File sidebar form fields not part of tabindex (not keyboard navigable)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#177]
## Tasks
- [x] Auto-focus happens for the Editor when it is opened (either by Editing a file/folder, or creating a folder)
- [x] Gallery is hidden (display none) when on small screen, not just covered by the Editor.
- [x] Gallery and Editor is both shown (and can both be tabbed through) in that order when the screen is large enough.

## Pull requests:

- [x] https://github.com/silverstripe/silverstripe-framework/pull/6919
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/473
- [x] https://github.com/silverstripe/silverstripe-admin/pull/68

**Comment by clarkepaul** [comment]
They are but they appear before galleryItems. I moved the Editor panel before the Gallery so that the Gallery could be resized based on whether or not the Editor markup was present. We could change the order of Gallery and Editor back if there was a bit of JS to say if Editor is present.

**Comment by chillu** [comment]
@clarkepaul How much effort is it to move editor markup after gallery markup? It's an accessibility issue, right?

**Comment by clarkepaul** [comment]
There is a good side to the way it currently is set up. Markup wise I think it makes more sense having the edit panel positioned before the gallery items, it also means the gallery resizes on the remainder of the space based on what has already been used by the edit panel. On smaller devices it actually makes more sense for tabbing to go from the menu to the selected item as it consumes the entire screen with the gallery living underneath.

The bad part is that tabbing through can be confusing so if possible I would prefer to adjust the ordering of the tabindex for larger screens only rather than the structure of markup.

**Comment by chillu** [comment]
> On smaller devices it actually makes more sense for tabbing to go from the menu to the selected item as it consumes the entire screen with the gallery living underneath.

I think only visible elements can be tabbed into, so that's a non-starter.

How about we just focus the first input field when opening the sidebar? That should guide screen readers enough as well. We're already doing this when opening a page from the CMS tree.

**Comment by scott1702** [comment]
> How about we just focus the first input field when opening the sidebar?

+1

Having the editor markup after the gallery would be annoying as a user would have to tab through all the images in the folder to get to the editor (would be helped a little by pagination). As it currently is it's also unclear that the user should tab through all the elements in the page again to get to the editor (or shift+tab). I agree that focusing on the first input field when opening the sidebar would be the best approach here.

**Comment by clarkepaul** [comment]
Yup shift focus would be perfect. I was expecting the items to remain under the edit panel on smaller devices so we could either animate the item expanding out from the selected item or slide the panel in from the side. It is fine as it is though for the time being.

**Comment by clarkepaul** [comment]
@flamerohr adding you just incase you resolve this as part of what you where doing in Alpha7.

**Comment by flamerohr** [comment]
@clarkepaul if the first field in the Editor gains focus on open, would that suffice to close this story, or did you think we'll need tabindex control still?

Not sure what the choice of action is

**Comment by clarkepaul** [comment]
Yeah actually I don't think that resolves this issue but certainly helps its UX. I think we still need to look at the order of the editor panel and gallery (so gallery comes first), and perhaps put hidden on gallery for smaller screens when the editor is visible so it doesn't receive focus.

**Comment by flamerohr** [comment]
@clarkepaul yeah, that's a good point... I'll put in the Tasks for this: add responsive class logic to hide the gallery when the screen is small enough.
The Gallery and Editor should both be showing (in that order) when on a large screen.
