### ISSUE TITLE
Move files and folders via new folder location selection in "edit folder"

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#217]
## Acceptance Criteria
- In the "edit folder" sidebar, allow selecting a new folder (https://projects.invisionapp.com/boards/TNX68PHXRJS3/)

## Excludes
- Search in TreeDropdownField

## Tasks
- [x] Add a location field to file and folder forms
- [x] Make sure path field is shown below the location field
- [x] Add API to "add a selectable item to the list for *(root)*" in TreeDropdownField
- [x] Add API to customise the empty title for TreeDropdownField
- [x] Investigate bug where changing location (by changing ParentID) twice without browsing  - bug is due to redux-form retaining the old Tuple and submitting that instead of the new Tuple value from the File move during submit.
- [x] Investigate bug where url was not matching gallery folder opened (it changes when saving the new location)
- [x] Behat tests

## Notes

- Drag'n'drop already exists, but only allows moving into an immediate child/parent folder
- This is a more clear way to move files and folders into a parent folder
- Use TreeDropdownField
- In the design, the field has additional functionality of being able to search directly from the field but for this issue search functionality is not required (later story).

## Related
- [Move files and folders via drag/drop on gallery view](https://github.com/silverstripe/silverstripe-asset-admin/issues/216)
- [Upload files into folders via drag/drop](https://github.com/silverstripe/silverstripe-asset-admin/issues/104)

## Pull requests
- [x] https://github.com/silverstripe/silverstripe-framework/pull/6915
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/476
- [x] https://github.com/silverstripe/silverstripe-admin/pull/67
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/73
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/6924

**Comment by sminnee** [comment]
I'd say that this is lower priority than drag and drop. I think we focused on this as a 'quick win' but maybe it's best just to make the drag and drop feature?

**Comment by chillu** [comment]
A React-based TreeDropdownField is in place now, so this should just be a matter of using it in this context.

**Comment by chillu** [comment]
The new React-based TreeDropdownField doesn't have a "root node" to select
