### ISSUE TITLE
Tidy up structure of File's formschema

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#253]
PR:
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/6178
 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/288

## Acceptance criteria:

 * File's form schema doesn't embed a tabset at the top level.
 * There's a way of extending File's detail fields. It's not `File::updateCMSFields()` – it's an object provided by asset-admin (probably a Form)
 * You are still able to create custom tabs in the 2nd half of the form.

To consider:

 * Proof of Concept - scaffolder for Controller-Model relationship which generates the form
 * Should the field list provided for editing files be a separate class within asset-admin, rather than a method on the File object?

----

Was: Additional unwanted tab panel hidden within Edit panel

Not sure why there would need to be tab panel surrounding everything in the edit panel, this doesn't effect and visuals to my knowledge but could potentially break stuff. The inner nested tab set is good though with "Details" and "Usage".

![image](https://cloud.githubusercontent.com/assets/555033/18539964/5a337390-7b6f-11e6-9a7d-a03e71144b54.png)

## Tasks

- [x] Remove top-level tabset from form file edit schema
- [x] Extension hook for editing form file edit schema on AssetAdmin
- [x] Create class which will scaffold form fields
- [x] map out ideas for Injector

**Comment by sminnee** [comment]
Yeah, this is a hangover of SS3 applied to the new react form. The `getCMSFields()` content for File details shouldn't have forms in there just because we had that in SS3.

**Comment by sminnee** [comment]
Assigning this to the react-forms epic as it kind of impacts how we think about the FormSchemas provided by the files.

**Comment by tractorcow** [comment]
PR created: See top comment. :)

**Comment by tractorcow** [comment]
Updated based on changes to framework PR.
See https://github.com/silverstripe/silverstripe-framework/pull/6178#issuecomment-254092537

**Comment by sminnee** [comment]
This is done now.

**Comment by tractorcow** [comment]
Thanks very much @sminnee !
