### ISSUE TITLE
List view for files

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-asset-admin#278]
## Acceptance criteria

- Designs are finalised
- I can switch between gallery view and list view on any folder of the asset admin
- I can see [tbc] columns in the list view
- I can click a column header to sort by that column
- Pagination works (either infinite scroll or actual page list)
- list vs gallery view indicated in the URL, as does sorting and current page. querystring is fine
- Shifting between gallery view and list view doesn't unnecessarily cause a refresh from server (i.e. it's using the same piece of redux state). Partial refresh due to the showing different pages of data is allowed.

Excluded

 - Column selector control for narrower width devices (separate story)
 - Multi-select for batch actions (separate story)

https://projects.invisionapp.com/boards/9GX68PTXUQFH#/1547737/129314959

# Dependency
https://github.com/silverstripe/silverstripe-asset-admin/issues/173 - because it has a lot of the url param and routing rework required for functionality such as sorting.

# Tasks
- [x] Add view switch function/component
- [x] Separate tile view to a component
- [x] Create list view component
- [x] Implement column sorting
- [x] Pagination (with page links/numbers)
- [x] Docblocks
- [x] Unit tests

# Front-end tasks
- [x] Thumbnail size and list size have same height
- [x] Toggle button size increase (not blurry)
- [x] Checkbox and thumb column at 1%
- [x] Pagination to match rest of CMS pagination
- [x] Remove additional ascending/descending character ▲
- [x] Browser testing

Opening as separate issues:
- Turn sort by into icon 
- Adjust small folder and doc icons so not blurry
- While loading table the editor panel floats in centre of screen (not fixed right)

# Pull requests
- https://github.com/silverstripe/silverstripe-asset-admin/pull/327
- https://github.com/silverstripe/silverstripe-framework/pull/6371

**Comment by clarkepaul** [comment]
Visual direction for list view of items:
https://projects.invisionapp.com/boards/2JX68PNPDF6K/

The toggle for List vs Thumbnail view is to be simplified to a show an icon for the opposite view. e.g. if the user is viewing the thumbnail view then show the list view icon and vice-versa.
https://projects.invisionapp.com/boards/JKX68PN94BSP/

**Comment by flamerohr** [comment]
I had a quick look around for modules and compared [Griddle](http://griddlegriddle.github.io/Griddle/index.html) vs [Facebook's fixed-data-table](https://facebook.github.io/fixed-data-table/getting-started.html)

## Griddle has a lot of features built in and has some strong opinions built in, features include:
- Sorting
- Pagination
- Lazy loading
- Columns/Filtering

### Notable issues
- uses internal state, so may present issues when working with Redux
- Version 1.0 coming up, release date is undetermined.

## fixed-data-table features are:
- Fixed headers and footers
- Performance for large datasets

### Notable issues
- Sorting, Pagination and Filtering will need to be done by a wrapper, so it will work with Redux
- Seems to have low activity, but time will tell.
- height and width are set, not sure if it means all cells has to be fixed.

**Comment by chillu** [comment]
* fixed-data-table is semi-abandoned: https://github.com/facebook/fixed-data-table/issues/408#issuecomment-223377136, so doesn't have the "big name backing" benefit for us. Might still prove the better product, but it's on more even footing with Griddle for me now
 * Griddle is [focusing](https://github.com/GriddleGriddle/Griddle/issues/276) on plugin infrastructure in 1.0 which we'll likely rely on, e.g. for inline editing or batch selection
 * There's a Griddle module for SS already: https://github.com/Tom-Alexander/silverstripe-griddle
 * http://allenfang.github.io/react-bootstrap-table/ is another contender with similar number of contributors, more features (e.g. inline edit), but it seems a bit monolithic
 * @unclecheese comment: "gridfield is the most nightmarish thing to bring into react, IMO"

**Comment by clarkepaul** [comment]
@flamerohr Can you use the latest version of the toggle which only shows a single icon (only showing the icon of the option you can switch too). I haven't really decided where the sort and toggle would fit best (far top right or gallery top right) as this area isn't that consistent with other sections yet so you can just put the toggle to the right of the current sort position.
https://projects.invisionapp.com/boards/JKX68PN94BSP/
https://projects.invisionapp.com/boards/WEX68PM3XJ2N/

**Comment by flamerohr** [comment]
Cool, I've put it gallery top right for now. Thanks @clarkepaul

**Comment by clarkepaul** [comment]
Some feedback, I guess it would be good for me to jump in and help on adjusting these styles?
![pasted_image_1_12_16__3_40_pm](https://cloud.githubusercontent.com/assets/555033/20780302/cb247ef4-b7de-11e6-9406-1f1a07d37a05.png)

**Comment by chillu** [comment]
https://github.com/open-sausages/silverstripe-framework/tree/pulls/4.0/gallery-list
https://github.com/open-sausages/silverstripe-asset-admin/tree/pulls/4.0/gallery-list

**Comment by clarkepaul** [comment]
@flamerohr are you able to help me remove this old arrow ( ▲) from the markup as I'm adding it with styles? 
![image](https://cloud.githubusercontent.com/assets/555033/20913253/f688af20-bbda-11e6-8455-3fb4b9c4a55f.png)

If not I could make it the same color as bg but thats a hack.

**Comment by flamerohr** [comment]
@clarkepaul I've pushed a commit up which removed them

**Comment by clarkepaul** [comment]
cheers

**Comment by clarkepaul** [comment]
Made pagination work up to 6 characters deep. 
![image](https://cloud.githubusercontent.com/assets/555033/20954115/47e14e64-bc9d-11e6-951e-4fcdd305439f.png)

**Comment by clarkepaul** [comment]
Good for rebase then review. I think it might be safer you rebase @flamerohr as it might be more React issues? otherwise I will ry tomorrow.

**Comment by flamerohr** [comment]
thanks @clarkepaul I'll rebase tomorrow :) there's one commit I haven't pushed because it was moving files around
