### ISSUE TITLE
History view on a file

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-asset-admin#294]
As an author, I want to see the history of changes to a file, so that I can audit what was published on a given day, and who has made changes

## Acceptance criteria
- I can see the history of changes to a file in the UI
- I can see who made changes
- I can see old meta-data
- I can view old versions of a file only if this feature is enabled in my SilverStripe installation
- I can view the old versions of the file if I am logged in as an appropriate user
- I can see published vs unpublished versions
- Versions are sorted newest first

Exclusions

 - No compare mode
 - No re-sorting
 - No revert functionality
 - No pagination
 - Using graphql ( as we don't want to go down that rabbit hole just yet - Ingo)

## Tasks

- [x] Write behat test to open a file and view history list shows correct data, modifying a file updates the UI and on revert the user receives a message (assume revert logic / permissions is covered by unit level tests).
- [x] Write basic unit level for content API endpoint which loads the history data.
- [x] Build content API endpoint in asset-admin server side for providing a JSON object of data to React. 
- [x] Ensure history has correct permission filtering.
- [x] Ensure files with large histories do not cause excessive server load 
- [x] Build React Component(s) for history item, readonly form and DOM for history tab viewer
- [x] If previous thumbnail not stored by SilverStripe, display a notice message.
- [x] Ensure tests pass.
- [x] Smoke test on various cases (no history, recently uploaded file, recently changed file..)
- [x] Design review with Paul
- [x] Browser Test IE
- [x] Browser Test Chrome
- [x] Browser Test Firefox
- [x] Browser Test Safari

Pull request: https://github.com/silverstripe/silverstripe-asset-admin/pull/306

**Comment by clarkepaul** [comment]
Design concept, feedback welcome https://projects.invisionapp.com/boards/5CX68PWMSYVK/

**Comment by clarkepaul** [comment]
More advanced version based on feedback with functionality to restore and view the changes like you would with pages. https://projects.invisionapp.com/boards/BXX68PGVNWFR/

I'm not sure this version is a must have for the majority of people but would be a nice addition.

**Comment by clarkepaul** [comment]
Just had a chat to @sminnee and he is good with the second design with revert. @wilr with the historic preview lets cap the max-height at 100px, the doc thumbs are 92px so they would look okay there as well.

I don't think the cancel button in my design is even necessary.

**Comment by wilr** [comment]
@flamerohr @chillu @tractorcow Considering this is my first piece of any react / SS4 work keen to make sure it's https://github.com/wilr/silverstripe-asset-admin/compare/master...wilr:294-history-view. This achieves all the acceptance criteria on the card. Behat Test is still a work in progress.

**Comment by clarkepaul** [comment]
A few things:
* Changing the file name causes the file to be missing [cannot be found]
* Missing date time when published, relevant if a lot of changes are happening in a short time frame by multiple people

* I've hardcoded version number and date to item details, can these be dynamic?
* Date time not need if file is only saved (only if published—couldn't mock that)
![pasted_image_22_11_16__3_18_pm](https://cloud.githubusercontent.com/assets/555033/20508540/2640b934-b0c7-11e6-8a72-7f6ee499bab3.png)

* Each field changed should be a new line for ease of reading
![pasted_image_22_11_16__3_14_pm](https://cloud.githubusercontent.com/assets/555033/20508448/9d71c4b8-b0c6-11e6-8df9-a650c3d86823.png)

Will make a PR for my changes as I've changed up quite a few classes and CSS

**Comment by wilr** [comment]
Added behat test.
