### ISSUE TITLE
File replacement action

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-asset-admin#295]
As a user, I want to be able to replace a file, so that I can have a new file downloaded from an existing URL.
## Acceptance criteria
- On the file detail view, there is a replace action, that allows the uploading of a single file
- If the replace action is used, the resulting URL is the same as the previous file, and the old file is tracked in the version history
- If you upload a file with a different extension, it warns that the URL will change
- If you upload a file with an invalid extension, it will throw an error

Exclusion

- When bulk uploading files, if there is a file of the same name already in the folder, an option to replace exist (separate story)

## Tasks
 - [x] Create a preview image component, which handles rendering the preview and icon-bar to the right.
 - [x] Update FormFactory to use the preview image component. This allows the submission of new file tuple (Filename, Hash, Variant) to replace the contained DBFile.
 - [x] Show progress of upload for replacement
 - [x] Add endpoint for uploading the replacement image.
 - [x] Ensure that component is updatable via state (from form submission returning updated formschema state).
 - [x] Check for different file extension and display a warning
 - [x] Unit tests
 - [x] Behat tests

# Pull requests
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/339
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/6428

**Comment by flamerohr** [comment]
User flow for replacing file, I think, goes something like this:

1. User opens the Editor for a file.
2. User clicks "Replace" call-to-action button.
3. Modal opens with Upload Field for user to provide replacement file for.
4. User will get a confirmation with warnings.
5. User clicks "Ok" for the confirmation and upload happens replacing file, retaining filename where necessary.

**Comment by clarkepaul** [comment]
This was wireframe produced by @scott1702 way back but it doesn't really suit.
https://invis.io/C596UOLDZ#/117448956_SilverStripe_UI_Copy_PS_Edit_File

As you described @flamerohr but we just need a browse window and once you chose a new file it would upload in place of the old image with progress bar. 
The image would only be updated once "Save" is selected I'm thinking but not sure on that one?

**Comment by clarkepaul** [comment]
Something I'm thinking about... Once you select the replace action would it be weird to bring up the files area in the modal (same as the insert into pages modal) so the user can replace with an existing file or upload a new one.

**Comment by flamerohr** [comment]
I've discussed this with @clarkepaul and we both agree that we should address this https://github.com/silverstripe/silverstripe-asset-admin/issues/173 file picker story before doing this one.
As behaviour isn't quite decided on yet, the file picker story will give us a chance to re-evaluate when we come back to this.

**Comment by clarkepaul** [comment]
We will need to rearrange the actions available on top of the file so they accessible on touch device (show all the time). These are my suggestions for the icons positioned on the right vertically centred. We should offer title text on hover if it is a link as the link has no text.

![image](https://cloud.githubusercontent.com/assets/555033/20908171/c125124c-bbb7-11e6-9b45-ab1a09e8479a.png)

**Comment by clarkepaul** [comment]
New icon is included in the updated set https://drive.google.com/a/silverstripe.com/file/d/0B8kr2MiImgr7XzVUY1RmZWxscEE/view?usp=sharing

**Comment by tractorcow** [comment]
@flamerohr I've updated the tasks slightly. :)

**Comment by flamerohr** [comment]
thanks @tractorcow

**Comment by flamerohr** [comment]
Branches are `pulls/4.0/replace-file` on `framework` and `asset-admin`

**Comment by tractorcow** [comment]
Closed with #339
