### ISSUE TITLE
 Gallery View & Create Folder uses GraphQL

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#316]
As a developer, I want to use GraphQL as the API for the asset section, so that I have a consistent content API.

## Acceptance criteria:

 * Gallery view fetches files via GraphQL
 * Folder creation occurs via GraphQL

## Exclusions

 * `File::canView()` and `Folder::canCreate()` permissions are not checked (see https://github.com/silverstripe/silverstripe-graphql/issues/5)
 * ~~Pagination in gallery view~~ (included this now)

## Tasks

 * [x] Rebase on master
 * [x] Pagination in list view (see [issue](https://github.com/silverstripe/silverstripe-asset-admin/issues/278))
 * [x] Pagination in gallery view (see [issue](https://github.com/silverstripe/silverstripe-asset-admin/issues/278))
 * [x] Sort on files (dropdown and table sort)
 * [x] Respect sort when adding new folder after mutation
 * [x] Fix folder navigation (currently defaults to `undefined`) - might be fixed by [rebase](https://github.com/silverstripe/silverstripe-asset-admin/issues/316)
 * [x] Fix persistence of uploaded files in current view
 * [x] Only refetch() once after all uploads complete (not every one)
 * [x] Don't show "no items" when loading data (e.g. during pagination)
 * [x] Merge custom sort for GraphQL (https://github.com/silverstripe/silverstripe-graphql/pull/24)
 * [x] Merge case accessor patch (https://github.com/silverstripe/silverstripe-graphql/pull/31)
 * [x] Test with "select file" in UploadField
 * [x] Fix existing unit tests
 * [x] Write at least one GraphQL related unit test (e.g. GraphQL query triggered on folder delete)
 * [x] Fix behat tests
 * [x] Cross browser tests
 * [ ] Pagination is broken when uploading first file
 * [ ] GraphQL resolver allows duplicating folder names
 * [ ] PHPDoc for GraphQL classes in asset-admin

## Notes

 * (Was: Rebase and merge GraphQL work)
 * See https://github.com/silverstripe/silverstripe-framework/issues/6245. Applies to both `framework` and `asset-admin` repos.

**Comment by chillu** [comment]
Pull request is being prepared in the following branches:
https://github.com/open-sausages/silverstripe-asset-admin/tree/pulls/4.0/graphql
https://github.com/open-sausages/silverstripe-framework/tree/pulls/4.0/graphql

**Comment by chillu** [comment]
Pull requests for peer review:
https://github.com/silverstripe/silverstripe-framework/pull/6420
https://github.com/silverstripe/silverstripe-asset-admin/pull/338

**Comment by tractorcow** [comment]
Reviewing this.
