### ISSUE TITLE
Need option to not-inline protected thumbnails

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-asset-admin#550]
For certain backends (e.g. s3) it's more performant to use signed urls than inline content, as protected thumbnails can be served quicker directly through secure s3 urls.

We need an option on FileTypeCreator::resolveThumbnailField() to invoke getURL() even on protected thumbnails.

This option still needs to be OFF by default, but it should be easy to turn on via yml config.

Part of https://github.com/silverstripe/silverstripe-assets/issues/52

# Acceptance Criteria

 - When using s3 assets thumbnails are served via direct urls rather than inline content
 - https://github.com/madmatt/silverstripe-s3/pull/7 is implemented

# Tasks

 - [x] Add config to asset admin to make thumbnail method configurable
 - [x] Ensure s3 module disables inline thumbnails
 
# PRs

 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/552
 - [x] https://github.com/madmatt/silverstripe-s3/pull/9
