### ISSUE TITLE
File labels are confusing

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#554]
## ACs
As a CMS user I want to see side panel labels clearly defined, so I can understand what information is presented within the fields below.
* Folders name field should be labeled as "Folder name"
* Files name field should be labeled as "Filename"
* FolderLocation is two words and should be presented as two words "Folder location"

## Pull requests
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/579

## Tasks
**Revised Labels for folders side panel**
- [x] Rename "Filename" label to "Folder name"
- [x] Rename Filename invalid error message from "Filename is required" to "Folder name is required"
- [x] Rename "FolderLocation" label to "Location"
![screen_shot_2017-08-07_at_14_56_20](https://user-images.githubusercontent.com/8085295/29048856-e70a87f0-7c26-11e7-86e5-61e1a5812cd4.png)

**Revised Labels for files side panel**
- [x] Rename "FolderLocation" label to "Location"
![screen_shot_2017-08-07_at_14_53_35](https://user-images.githubusercontent.com/8085295/29048861-f0675b16-7c26-11e7-8163-71a87aaf1ea9.png)

**Comment by clarkepaul** [comment]
Based on team discussions: Ideally, we want to hide the move tree dropdown and only show it when the user wants to move the file. We can create a few mock-ups with different approaches and present them back here for feedback. 
Designs will include a batch move, individual moving of files could be accessible from the items "more options" area or a link from the path to edit it.

**Comment by clarkepaul** [comment]
Folder name is also confusing being Filename.
![image](https://user-images.githubusercontent.com/555033/28850228-8aaf81ba-776f-11e7-9d0f-21cdcd75f014.png)

**Comment by clarkepaul** [comment]
Updated the title and AC's of this issue so it is just for relabelling of the fields and we have separated the changing of location part to another issue https://github.com/silverstripe/silverstripe-asset-admin/issues/576
