### ISSUE TITLE
Not all files can be placed into a WYSIWYG area (only images in SS4)

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#563]
User can't place files of the type docs, audio, video into a WYSIWYG area (If they try they get an error). In SS3 you can select any file into the text editor (files other than images are placed as links) but with SS4 you can only place images. 

If we don't match SS3 functionality we need to provide clarity that certain files can't be placed by either not making them available or disabling the insert functionality (with notification this file type can not be inserted) 

## AC's
As a CMS user, I would like to:
- be notified when a particular file type is cannot be inserted onto a page.
- have the ability to insert an unsupported file as a link.
- clearly understand the difference between inserting content from "Files" and embedding content from offsite. (Related to https://github.com/silverstripe/silverstripe-admin/issues/169)

## Tasks
- [x] Add notification to side panel when selected file cannot be properly inserted
- [x] Enable files the are currently not supported to be inserted as links (as per design below)
- [x] Replace existing content under "Placement" tab with "Link text", "Filename" and "URL" read only fields.
- [x] Change text of "insert file" button to "Insert link"
- [x] Style notification message

## Prototype:
https://invis.io/4NCYDMWEW#/247738949_Page_-_TinyMCE_-_Insert_Media_-_Home

## Pull request:

- ~https://github.com/silverstripe/silverstripe-asset-admin/pull/585~
- [x] https://github.com/silverstripe/silverstripe-admin/pull/204
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/596

**Comment by tractorcow** [comment]
You can add a link to a file. I know because I just did it. :)

![image](https://user-images.githubusercontent.com/936064/28565907-b46e1b18-7181-11e7-8dad-51561404de3b.png)

![image](https://user-images.githubusercontent.com/936064/28565925-be6eaed4-7181-11e7-821a-1fc8dae80cce.png)

**Comment by tractorcow** [comment]
ok, so if you use "insert media" with an image file you get this error.

![image](https://user-images.githubusercontent.com/936064/28595427-ee1ae7d6-71e7-11e7-9ca3-d926413c4783.png)

Should the point of this issue be to address / fix this?

**Comment by clarkepaul** [comment]
I'll add a bit more context above ^

**Comment by tractorcow** [comment]
The above line is still incorrect.

> In SS3 you can place any file into the text editor (placed as links) but with SS4 you can only place images.

You can place these files as links in SS4. What doesn't work is embedded non-image media (video, flash) from local assets.

Non-media files (e.g. pdf, text) could never be embedded, and have always been able to (and currently can be) placed as links.

**Comment by flamerohr** [comment]
> In SS3 you can place any file into the text editor (placed as links) but with SS4 you can only place images.

You can place files as links in SS4, it's a different interface (ala, the insert file link modal)

I don't think it's a good idea to cross-wire the expectations of placing a **link** with placing an **image** or **embedded media**

**Comment by clarkepaul** [comment]
Okay cool, but what I meant is any file can be selected in SS3 but in SS4 only images can be selected. I don't think it should insert files other than images as links either but that would at least be better than the way it works now. I'm in favour of this, but would take a fair amount of dev time.
> Allow users to place any file type in the Files area into WYSIWYG areas but we provide the functionality to visually place the media into the content area. eg Video's can be played, audio files can be played, docs are presented with the file name and file type icon, if supported by the browser.

**Comment by clarkepaul** [comment]
Updated the text above again :)

**Comment by tractorcow** [comment]
I think we should try getting oembed working with the last option

>  Allow users to place any file type in the Files area into WYSIWYG areas but we provide the functionality to visually place the media into the content area. eg Video's can be played, audio files can be played, docs are presented with the file name and file type icon, if supported by the browser.

Does this suit you @clarkepaul ?

Let's do some exploration first.

**Comment by clarkepaul** [comment]
Great, yeah it needs a bit more investigation into the presentation and effort required because if it's a huge task, it might be more practical to go with one of the options as an MVP.

**Comment by tractorcow** [comment]
@clarkepaul I've done a bit of digging and I think I can see the kind of solution we could implement:

It's possible to implement an oembed provider that could serve oembed content for local assets.

See https://github.com/MediaDevils/silverstripe-oembed-endpoint for an existing proof of concept.

The new provider could implement the AssetStoreRouter interface, which takes an asset path (e.g. 'file/video.mp4' and returns a HTTPResponse (e.g. html content with '<video>' html markup).

How does this sound?

**Comment by clarkepaul** [comment]
Good, can this work with the same interface as inserting files from the files area (modal)?

**Comment by clarkepaul** [comment]
TODO: Design to outline any differences from images to other media types and what fields/interactions are required.

**Comment by flamerohr** [comment]
we could add the behaviour in to the insert media modal, so if a video is selected instead of an image it'll insert an embed
you possibly wouldn't need any fields changed, and we could use this chance to update the interface for inserting a file (e.g. replace dropdown with the icon list from external video embedding)

**Comment by clarkepaul** [comment]
Cool, needs AC's and can task out before going forward.

**Comment by newleeland** [comment]
What would the different file types be if we used oembed for local files (images, video, ...) @tractorcow 

I'd imagine we'd need new UI the new file types? How much effort do you think it would take?

**Comment by clarkepaul** [comment]
From my perspective, it would be good to cover videos, audio, and docs? ... anything else we could let them know they can't embed via the UI.

**Comment by newleeland** [comment]
As an MVP we should simply have a notification of some sort to indicate local files types that are not insertable. Additionally, we should make the names of the two media buttons more explicit. For example: (Relates to https://github.com/silverstripe/silverstripe-admin/issues/169)
![screen_shot_2017-08-08_at_3_36_17_pm](https://user-images.githubusercontent.com/8085295/29055343-12b6b63e-7c50-11e7-83b5-47fe07d68497.png)

However, if the oembed for local files is possible and straightforward to do, we should try to implement it. This would still require some sort of notification for file types that are not insertable (however user could create a link to file if they wished).

**Comment by flamerohr** [comment]
For practical reasons, please limit to `image` and `video` embedding ;)

And could extend to `audio` later (e.g. we don't have a proof of concept for that yet)

I'm wary of allowing `document` embeds because that opens a giant can of worms to maintain, historically speaking. And also the lack of proof of concept for this one as well.

**Comment by clarkepaul** [comment]
I'd be okay with that.

**Comment by newleeland** [comment]
I'm going to split this file into another story so we're not bogged down with trying to support everything. So that this story is just to notify the user if the file type is not supported and give them the ability to insert it instead as a link.

I'll create another story to implement support for video, audio and documents in the backlog.

**Comment by clarkepaul** [comment]
I've removed the label changes and moved them to their own issue @newleeland

**Comment by phalkunz** [comment]
@newleeland I've got feedbacks from @assertchris:

- "Link text" field should be editable
- When inserting an unsupported media, the insert form should be Insert link form, rather than customised insert media form

 What do you think?

**Comment by tractorcow** [comment]
Related: https://github.com/silverstripe/silverstripe-asset-admin/issues/580
