### ISSUE TITLE
Bulk move of files

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-asset-admin#578]
## AC's
As a user, I should:
* have a way to select multiple files (already built)
* be presented with an action to move multiple items which are intuitive
* have the ability to select multiple files to move collectively to a new folder location at any depth of the hierarchy of my choosing in the Files area
* be provided with a good indication of where the files have been moved
* be provided with a similar interaction as the moving of a single file https://github.com/silverstripe/silverstripe-asset-admin/issues/576

Out of scope: "Undo"

## Tasks
* [x] New batch action for bulk move
* [x] New dialog for "select destination" (treedropdown)
* [x] Display message (success or failure)
* [x] Message above the dropdown field in the modal
* [x] Behat tests
* [x] Add "Add folder" svg to fontastic
* [x] Update CMS with new font icons (May be completed with #576 ) https://github.com/silverstripe/silverstripe-admin/pull/190
* [x] i18n

## PRs

- [x] https://github.com/silverstripe/silverstripe-admin/pull/190
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/592
- [x] https://github.com/silverstripe/silverstripe-admin/pull/195

## Prototype
Move for files: https://invis.io/AKCZSFOWX#/247323908_Files_-_Edit_File_-_Move_Multi_File
Move for folders: https://invis.io/YRCZSG34B#/247323905_Files_-_Edit_File_-_Move_Multi_Folder

**Related**
https://github.com/silverstripe/silverstripe-asset-admin/issues/576

**Comment by tractorcow** [comment]
Updated https://github.com/silverstripe/silverstripe-admin/pull/190
