### ISSUE TITLE
Leverage new Apollo 2.x APIs

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-asset-admin#781]
Once https://github.com/silverstripe/silverstripe-asset-admin/pull/780 is merged, we need to start taking advantage of the new [imperative cache API](https://www.apollographql.com/docs/react/advanced/caching.html). This will go a long way to improving the user experience and overall performance of the asset-admin module.

## Tasks
- [ ] `moveFilesMutation` needs to use cache read/writes
- [ ] `createFolderMutation` needs to use cache read/writes
- [ ]  Remove imperative (and unnecessary) `readFiles` call in `handleMoveFilesSuccess`, and instead rely on optimistic updates via cache
- [ ] Remove imperative (and unnecessary) `handleBrowse` call in `handleCreateFolder` and instead rely on optimistic updates via cache

## More information
See `deleteFilesMutation` in the above PR as an example of how this will work.
